### ISSUE TITLE
Let's formulate all the requirements here..

### ISSUE THREAD

**Issue by JainamJhaveri** [psp65/ourproject#5]
Let's formulate all the requirements  in a paragraph format first, then we would be able to deduce the tables and attributes faster... What do you all say ?

**Comment by psp65** [comment]
Like, One essential thing is, how to identify that, weather a Student is rating a faculty for the first time or not? As, there are many students & faculties there is many to many relation.

To overcome that, we need a new table with 2 foreign keys of student_id & fac_id. Is it possible to have this kind of table?? ie.

before_rated 
            user_id (foreign key 1)         
            fac_id (foreign key 2)
            before_rated number(1) -- VALUE=0 if No else 1


Is it legit?

**Comment by psp65** [comment]
alignment issues in the previous one:

table before_rated 
      user_id (foreign key 1)
      fac_id (foreign key 2)
      before_rated number(1)  -- VALUE=0 if No else 1

**Comment by JainamJhaveri** [comment]
'Faculty Rater App' is to be made for the students 
so that they can rate the faculties on the basis of 3 criteria(intelligence, teaching, friendliness).
Students will judge the faculties based on their perception.


There are n (4000+)  students in a university
And there are m (around 300) faculties in a university


Each student has a unique studentid, studentname, branch associated with him.
	Branches can be:
		Civil, Mechanical, Chemical, Computer, IT, EE, EC, IC
	A student can belong to only one branch


Each faculty has a unique facultyid, facultyname, dept, post under which he works.
	There can be a faculty, who is not registered under any dept. (Visiting faculties or Faculties from different institutes)
	Department can be: 
		Civil, Mechanical, Chemical, Computer Science(Computer+IT), Electrical(EE, EC, IC)
		
	Posts of the faculties can be:
		HOD, Professor, Assistant Professor, Associate Professor, Visiting Faculty, ..
		A faculty can have only one post.
		
		
Note:
*Any student* (of any branch) *can rate any faculty* (belonging to any dept).


***------------------------------------------------------------------------------------------------------------------------------***
***------------------------------------------------------------------------------------------------------------------------------***

The ratings by each student for each faculty should be stored, 
hence there must be a relation between fac_stud_rated_or_not, 
which can contain table attributes as faculty_ids
and row beginner names as student_ids

Eg: 

ROLLCALLS		PSK		KKM		AA	...... 300 columns
-----------------------------------
13BCE002		1    	0   	1
13BCE005		1    	1   	1
13BCE010		0   	0   	1
13BCE015		1    	0   	1
13BCE020		0    	1   	1
13BCE025		1    	1   	1
.......
.......
.......
.......
.......
4000 records

Following info. can be deduced
	4 Students have rated for PSK, 3 for KKM and 6 for AA
	13BCE002 has yet not rated KKM, 13BCE010 has not rated PSK and KKM and so on..

***------------------------------------------------------------------------------------------------------------------------------***
***------------------------------------------------------------------------------------------------------------------------------***



I Will keep editing this post ..  and add table names and attributes ..

**Comment by harshil007** [comment]
One thing we can do is that we can create tables for each faculties which would make it easier to fetch the data for that faculty and also to keep track of how many and which students rated that faculty..
P.S. - I know that there are over 100 faculties and this method would increase the storage space required for db but it would make other tasks much easier
P.S.S - open to criticism and suggestions
P.S.S.S - I <3 Ria

**Comment by JainamJhaveri** [comment]
@harshil, it would be gr8, if you could elaborate on how would it make other tasks easier? I mean, it would making a table each for a faculty, would result in excess data replication( as we need to repeat the 1st column of rollcalls in each table).

**Comment by harshil007** [comment]
I think it would be better if i explain this is person..
so lets discuss this tommorow

**Comment by Dipshil** [comment]
no no no i disagree

**Comment by JainamJhaveri** [comment]
Tables that I have come up with

studentmaster(*sid*, sfname, smname, slname, **branchid**)
facultymaster(*fid*, ffname, fmname, flname, **deptid**)
branchmaster(*branchid*, branchname)
depmaster(*deptid*, deptname) 
student_faculty_master(***sid, fid***, r1, r2, r3)
// r1--> 1st cat.. // r2--> 2nd cat.. // r3--> 4th cat.. 


We can execute most( all according to  my knowledge )  queries and this solves the problem of distinguishing 1st time users to users who have atleast once casted their vote..

**Comment by JainamJhaveri** [comment]
Tables that Dipshil and I have come up with : 
------------------------------------------

studentmaster(**sid**, sfname, smname, slname, *branchid*)
student_rated(*sid*, f_rated)

facultymaster(**fid**, ffname, fmname, flname, *deptid*)
faculty_rating(*fid*, totalr1, totalr2, totalr3, total_raters)

branchmaster(**branchid**, branchname)
depmaster(**deptid**, deptname) 

student_faculty_master(*sid, fid*, r1, r2, r3)

**Comment by psp65** [comment]
student's & faculty's middle names can be omitted.

**Comment by JainamJhaveri** [comment]
Done

**Comment by psp65** [comment]
No need to separate student & faculty in terms of branch & dept.
Only one from this 2 is sufficient man!

ie.Only 
depmaster(deptid, deptname)

which also changes one property of the foll table,

studentmaster(sid, sfname, smname, slname, deptid)

**Comment by psp65** [comment]
Students of CE-IT are from, CSE dept
EE-EC-IC are from, EE dept...

**Comment by JainamJhaveri** [comment]
Are ek j comment ma edit karne

**Comment by psp65** [comment]
nani nani comments vanchvani maja ave :p

**Comment by JainamJhaveri** [comment]
But if we would like to know that how many students of IT branch have rated for a particular faculty.. Then?

**Comment by psp65** [comment]
But why to do so...??!!

& if you want to do that then your tables are good!

**Comment by JainamJhaveri** [comment]
*our

**Comment by dishankmehta** [comment]
Looks good to me..!

**Comment by JainamJhaveri** [comment]
And yes, regarding Harshil and Dishu's idea of m(300+) tables... I have found that DML queries on the go are extremely costly compared to DDL queries. We must not give power to the users, to make a table

**Comment by Dipshil** [comment]
i think student faculty master table is no more needed. we can define a
structure in student_rated which includes f_id ,r1,r2,r3 all together...but
for that deeper insight is needed about define.

**Comment by JainamJhaveri** [comment]
There's no student_fac_master table anymore Dipshil

**Comment by dishankmehta** [comment]
Okay jainam then we should drop the idea of tables 300+

**Comment by JainamJhaveri** [comment]
+1
